#!/bin/bash

# RayanPBX .env Configuration TUI
# Interactive configuration tool for .env file

# Colors
readonly GREEN='\033[0;32m'
readonly RED='\033[0;31m'
readonly YELLOW='\033[1;33m'
readonly CYAN='\033[0;36m'
readonly BLUE='\033[0;34m'
readonly MAGENTA='\033[0;35m'
readonly BOLD='\033[1m'
readonly DIM='\033[2m'
readonly RESET='\033[0m'
readonly REVERSE='\033[7m'
readonly REVERSE_OFF='\033[27m'

# Configuration variables
declare -A CONFIG
ENV_FILE="${1:-.env}"
ENV_EXAMPLE="${2:-.env.example}"

# Load existing config
load_config() {
    if [ -f "$ENV_FILE" ]; then
        while IFS='=' read -r key value; do
            # Skip comments and empty lines
            [[ $key =~ ^#.*$ ]] && continue
            [[ -z $key ]] && continue
            
            # Remove quotes
            value=$(echo "$value" | sed -e 's/^"//' -e 's/"$//' -e "s/^'//" -e "s/'$//")
            CONFIG[$key]=$value
        done < "$ENV_FILE"
    elif [ -f "$ENV_EXAMPLE" ]; then
        # Load from example
        while IFS='=' read -r key value; do
            [[ $key =~ ^#.*$ ]] && continue
            [[ -z $key ]] && continue
            value=$(echo "$value" | sed -e 's/^"//' -e 's/"$//' -e "s/^'//" -e "s/'$//")
            CONFIG[$key]=$value
        done < "$ENV_EXAMPLE"
    fi
}

# Save configuration
save_config() {
    local backup="${ENV_FILE}.backup.$(date +%Y%m%d_%H%M%S)"
    
    if [ -f "$ENV_FILE" ]; then
        cp "$ENV_FILE" "$backup"
        echo -e "${DIM}Backup created: $backup${RESET}"
    fi
    
    cat > "$ENV_FILE" << 'HEADER'
# RayanPBX Configuration
# Generated by RayanPBX Configurator
# Do not edit manually unless you know what you're doing

HEADER

    for key in $(echo "${!CONFIG[@]}" | tr ' ' '\n' | sort); do
        echo "${key}=${CONFIG[$key]}" >> "$ENV_FILE"
    done
    
    echo -e "${GREEN}✅ Configuration saved to $ENV_FILE${RESET}"
}

# Print banner
print_banner() {
    clear
    echo -e "${CYAN}${BOLD}"
    echo "╔══════════════════════════════════════════════╗"
    echo "║                                              ║"
    echo "║    🔧  RayanPBX Configuration Wizard  🔧     ║"
    echo "║                                              ║"
    echo "╚══════════════════════════════════════════════╝"
    echo -e "${RESET}\n"
}

# Input with default
input_with_default() {
    local prompt="$1"
    local key="$2"
    local default="${CONFIG[$key]:-$3}"
    local password="${4:-no}"
    
    echo -e "${CYAN}${prompt}${RESET}"
    if [ -n "$default" ]; then
        echo -e "${DIM}Current: $default${RESET}"
    fi
    
    if [ "$password" == "yes" ]; then
        read -sp "$(echo -e ${YELLOW}Enter value:${RESET} )" value
        echo
    else
        read -p "$(echo -e ${YELLOW}Enter value:${RESET} )" value
    fi
    
    if [ -z "$value" ]; then
        value="$default"
    fi
    
    CONFIG[$key]="$value"
}

# Yes/No question
ask_yes_no() {
    local prompt="$1"
    local key="$2"
    local default="${CONFIG[$key]:-$3}"
    
    echo -e "${CYAN}${prompt}${RESET}"
    if [ -n "$default" ]; then
        echo -e "${DIM}Current: $default${RESET}"
    fi
    
    read -p "$(echo -e ${YELLOW}[y/n]:${RESET} )" answer
    
    if [ -z "$answer" ]; then
        answer="$default"
    fi
    
    case "$answer" in
        [Yy]|[Yy][Ee][Ss]|true|TRUE)
            CONFIG[$key]="true"
            ;;
        *)
            CONFIG[$key]="false"
            ;;
    esac
}

# Generate random secret
generate_secret() {
    openssl rand -base64 32 | tr -d '\n'
}

# Get current Linux username
get_default_username() {
    local username=$(getent passwd | awk -F: '$3 >= 1000 && $3 < 65534 {print $1}' | head -1)
    if [ -z "$username" ]; then
        username=${SUDO_USER:-$(whoami)}
    fi
    echo "$username"
}

# Section: Application
configure_application() {
    print_banner
    echo -e "${BLUE}${BOLD}📱 Application Settings${RESET}\n"
    
    input_with_default "Application Name" "APP_NAME" "RayanPBX"
    input_with_default "Environment (local/production)" "APP_ENV" "production"
    ask_yes_no "Enable Debug Mode?" "APP_DEBUG" "false"
    input_with_default "Application URL" "APP_URL" "http://localhost:3000"
    input_with_default "Timezone" "APP_TIMEZONE" "UTC"
    
    echo
}

# Section: API
configure_api() {
    print_banner
    echo -e "${BLUE}${BOLD}🌐 API Configuration${RESET}\n"
    
    input_with_default "API Host" "API_HOST" "0.0.0.0"
    input_with_default "API Port" "API_PORT" "8000"
    CONFIG[API_BASE_URL]="http://localhost:${CONFIG[API_PORT]}"
    echo -e "${GREEN}✓ API Base URL set to: ${CONFIG[API_BASE_URL]}${RESET}"
    
    echo
}

# Section: Frontend
configure_frontend() {
    print_banner
    echo -e "${BLUE}${BOLD}💻 Frontend Configuration${RESET}\n"
    
    input_with_default "Frontend Port" "FRONTEND_PORT" "3000"
    input_with_default "Frontend Host" "FRONTEND_HOST" "0.0.0.0"
    
    echo
}

# Section: WebSocket
configure_websocket() {
    print_banner
    echo -e "${BLUE}${BOLD}📡 WebSocket Configuration${RESET}\n"
    
    input_with_default "WebSocket Host" "WEBSOCKET_HOST" "0.0.0.0"
    input_with_default "WebSocket Port" "WEBSOCKET_PORT" "9000"
    
    echo
}

# Section: Database
configure_database() {
    print_banner
    echo -e "${BLUE}${BOLD}🗄️  Database Configuration${RESET}\n"
    
    input_with_default "Database Connection Type" "DB_CONNECTION" "mysql"
    input_with_default "Database Host" "DB_HOST" "127.0.0.1"
    input_with_default "Database Port" "DB_PORT" "3306"
    input_with_default "Database Name" "DB_DATABASE" "rayanpbx"
    input_with_default "Database Username" "DB_USERNAME" "rayanpbx"
    input_with_default "Database Password" "DB_PASSWORD" "" "yes"
    
    echo
}

# Section: JWT
configure_jwt() {
    print_banner
    echo -e "${BLUE}${BOLD}🔐 JWT Authentication${RESET}\n"
    
    if [ -z "${CONFIG[JWT_SECRET]}" ] || [ "${CONFIG[JWT_SECRET]}" == "your-super-secret-jwt-key-change-this-in-production" ]; then
        echo -e "${YELLOW}Generating new JWT secret...${RESET}"
        CONFIG[JWT_SECRET]=$(generate_secret)
        echo -e "${GREEN}✓ JWT secret generated${RESET}"
    else
        echo -e "${GREEN}✓ Using existing JWT secret${RESET}"
        read -p "$(echo -e ${YELLOW}Generate new JWT secret? [y/N]:${RESET} )" regenerate
        if [[ "$regenerate" =~ ^[Yy]$ ]]; then
            CONFIG[JWT_SECRET]=$(generate_secret)
            echo -e "${GREEN}✓ New JWT secret generated${RESET}"
        fi
    fi
    
    input_with_default "JWT Algorithm" "JWT_ALGORITHM" "HS256"
    input_with_default "JWT Expiration (seconds)" "JWT_EXPIRATION" "7200"
    input_with_default "JWT Refresh Expiration (seconds)" "JWT_REFRESH_EXPIRATION" "604800"
    
    echo
}

# Section: Asterisk
configure_asterisk() {
    print_banner
    echo -e "${BLUE}${BOLD}📞 Asterisk Configuration${RESET}\n"
    
    input_with_default "Asterisk AMI Host" "ASTERISK_AMI_HOST" "127.0.0.1"
    input_with_default "Asterisk AMI Port" "ASTERISK_AMI_PORT" "5038"
    input_with_default "Asterisk AMI Username" "ASTERISK_AMI_USERNAME" "admin"
    input_with_default "Asterisk AMI Secret" "ASTERISK_AMI_SECRET" "rayanpbx_ami_secret" "yes"
    input_with_default "Asterisk Config Path" "ASTERISK_CONFIG_PATH" "/etc/asterisk"
    input_with_default "PJSIP Config File" "ASTERISK_PJSIP_CONFIG" "/etc/asterisk/pjsip.conf"
    input_with_default "Extensions Config File" "ASTERISK_EXTENSIONS_CONFIG" "/etc/asterisk/extensions.conf"
    input_with_default "Asterisk Log Path" "ASTERISK_LOG_PATH" "/var/log/asterisk"
    
    echo
}

# Section: SIP
configure_sip() {
    print_banner
    echo -e "${BLUE}${BOLD}☎️  SIP Configuration${RESET}\n"
    
    input_with_default "SIP Realm" "SIP_REALM" "rayanpbx.local"
    input_with_default "SIP Transport" "SIP_TRANSPORT" "udp"
    input_with_default "SIP Port" "SIP_PORT" "5060"
    input_with_default "SIP Codecs (comma-separated)" "SIP_CODECS" "ulaw,alaw,g722,opus"
    
    echo
}

# Section: RayanPBX specific
configure_rayanpbx() {
    print_banner
    echo -e "${BLUE}${BOLD}⚙️  RayanPBX Settings${RESET}\n"
    
    input_with_default "Extension Range Start" "RAYANPBX_EXTENSION_RANGE_START" "100"
    input_with_default "Extension Range End" "RAYANPBX_EXTENSION_RANGE_END" "999"
    input_with_default "Default Trunk Prefix" "RAYANPBX_DEFAULT_TRUNK_PREFIX" "9"
    ask_yes_no "Enable PAM Authentication?" "RAYANPBX_PAM_ENABLED" "true"
    
    echo
}

# Section: Security
configure_security() {
    print_banner
    echo -e "${BLUE}${BOLD}🛡️  Security Settings${RESET}\n"
    
    input_with_default "Login Rate Limit (attempts)" "RATE_LIMIT_LOGIN" "5"
    input_with_default "Login Rate Limit Decay (seconds)" "RATE_LIMIT_LOGIN_DECAY" "60"
    input_with_default "BCrypt Rounds" "BCRYPT_ROUNDS" "12"
    
    echo
}

# Section: Pollination AI
configure_pollination() {
    print_banner
    echo -e "${BLUE}${BOLD}🤖 Pollination.ai Integration${RESET}\n"
    
    ask_yes_no "Enable Pollination.ai?" "POLLINATION_AI_ENABLED" "true"
    
    if [ "${CONFIG[POLLINATION_AI_ENABLED]}" == "true" ]; then
        input_with_default "Pollination.ai API Key (optional)" "POLLINATION_AI_API_KEY" ""
        input_with_default "Pollination.ai Model" "POLLINATION_AI_MODEL" "gpt-4"
        input_with_default "Pollination.ai Endpoint" "POLLINATION_AI_ENDPOINT" "https://text.pollinations.ai"
    fi
    
    echo
}

# Section: CLI/TUI styling
configure_cli_styling() {
    print_banner
    echo -e "${BLUE}${BOLD}🎨 CLI/TUI Styling${RESET}\n"
    
    ask_yes_no "Use colors in CLI/TUI?" "CLI_USE_COLOR" "true"
    ask_yes_no "Use emojis in CLI/TUI?" "CLI_USE_EMOJI" "true"
    ask_yes_no "Use figlet banners?" "CLI_USE_FIGLET" "true"
    ask_yes_no "Use lolcat (if available)?" "CLI_USE_LOLCAT" "false"
    
    echo
}

# Enhanced menu selection with arrow key support
# Reads input with validation and displays it with reversed background
read_menu_option() {
    local valid_options=("1" "2" "3" "4" "5" "6" "7" "8" "9" "10" "11" "12" "Q" "q" "S" "s" "X" "x")
    local input=""
    local cursor_pos=0
    
    while true; do
        # Display prompt with space after colon and reversed background for input
        local display_input="${input:-  }"
        echo -ne "\r${YELLOW}Select option: ${REVERSE} $display_input ${REVERSE_OFF}${RESET}"
        
        # Read single character without echo
        IFS= read -rsn1 char
        
        # Handle escape sequences (arrow keys)
        if [ "$char" = $'\x1b' ]; then
            read -rsn2 -t 0.1 rest
            case "$rest" in
                '[A') # Up arrow
                    if [ $cursor_pos -gt 0 ]; then
                        ((cursor_pos--))
                        input="${valid_options[$cursor_pos]}"
                        # Display with reversed background
                        echo -ne "\r${YELLOW}Select option: ${REVERSE} $input ${REVERSE_OFF}${RESET}"
                    fi
                    ;;
                '[B') # Down arrow
                    if [ $cursor_pos -lt $((${#valid_options[@]} - 1)) ]; then
                        ((cursor_pos++))
                        input="${valid_options[$cursor_pos]}"
                        # Display with reversed background
                        echo -ne "\r${YELLOW}Select option: ${REVERSE} $input ${REVERSE_OFF}${RESET}"
                    fi
                    ;;
            esac
            continue
        fi
        
        # Handle Enter key
        if [ "$char" = "" ]; then
            if [ -n "$input" ]; then
                # Validate input is in valid options
                local valid=0
                for opt in "${valid_options[@]}"; do
                    if [ "$input" = "$opt" ]; then
                        valid=1
                        break
                    fi
                done
                
                if [ $valid -eq 1 ]; then
                    echo  # Move to next line
                    echo "$input"
                    return 0
                fi
            fi
            # Invalid or empty, stay in loop
            continue
        fi
        
        # Handle backspace
        if [ "$char" = $'\x7f' ] || [ "$char" = $'\x08' ]; then
            if [ -n "$input" ]; then
                input="${input%?}"
            fi
            continue
        fi
        
        # Check if character is digit, Q, S, or X (case insensitive)
        if [[ "$char" =~ ^[0-9QqSsXx]$ ]]; then
            # For single character options, auto-submit
            if [[ "$char" =~ ^[1-9QqSsXx]$ ]]; then
                # Check if this could be part of 10, 11, or 12
                if [ "$char" = "1" ] && [ -z "$input" ]; then
                    # Could be start of 10, 11, or 12
                    input="$char"
                    continue
                fi
                
                # Single digit or letter - validate and submit
                local test_input="$input$char"
                local valid=0
                for opt in "${valid_options[@]}"; do
                    if [ "$test_input" = "$opt" ]; then
                        valid=1
                        break
                    fi
                done
                
                if [ $valid -eq 1 ]; then
                    input="$test_input"
                    echo -ne "\r${YELLOW}Select option: ${REVERSE} $input ${REVERSE_OFF}${RESET}"
                    echo  # Move to next line
                    echo "$input"
                    return 0
                elif [ "$char" = "1" ] && [ -z "$input" ]; then
                    # Start of multi-digit
                    input="$char"
                else
                    # Invalid combination, ignore
                    continue
                fi
            elif [ "$char" = "0" ] && [ "$input" = "1" ]; then
                # Complete "10"
                input="10"
                echo -ne "\r${YELLOW}Select option: ${REVERSE} $input ${REVERSE_OFF}${RESET}"
                echo  # Move to next line
                echo "$input"
                return 0
            elif [[ "$char" =~ ^[12]$ ]] && [ "$input" = "1" ]; then
                # Complete "11" or "12"
                input="1$char"
                echo -ne "\r${YELLOW}Select option: ${REVERSE} $input ${REVERSE_OFF}${RESET}"
                echo  # Move to next line
                echo "$input"
                return 0
            fi
        fi
        # Invalid character - don't display or update
    done
}

# Main menu
main_menu() {
    while true; do
        print_banner
        echo -e "${BOLD}Configuration Menu${RESET}\n"
        echo "  1. 📱 Application Settings"
        echo "  2. 🌐 API Configuration"
        echo "  3. 💻 Frontend Configuration"
        echo "  4. 📡 WebSocket Configuration"
        echo "  5. 🗄️  Database Configuration"
        echo "  6. 🔐 JWT Authentication"
        echo "  7. 📞 Asterisk Configuration"
        echo "  8. ☎️  SIP Configuration"
        echo "  9. ⚙️  RayanPBX Settings"
        echo " 10. 🛡️  Security Settings"
        echo " 11. 🤖 Pollination.ai Integration"
        echo " 12. 🎨 CLI/TUI Styling"
        echo
        echo "  Q. Quick Setup (All Sections)"
        echo "  S. 💾 Save and Exit"
        echo "  X. ❌ Exit without Saving"
        echo
        
        # Use enhanced menu selection with validation
        choice=$(read_menu_option)
        
        case "$choice" in
            1) configure_application ;;
            2) configure_api ;;
            3) configure_frontend ;;
            4) configure_websocket ;;
            5) configure_database ;;
            6) configure_jwt ;;
            7) configure_asterisk ;;
            8) configure_sip ;;
            9) configure_rayanpbx ;;
            10) configure_security ;;
            11) configure_pollination ;;
            12) configure_cli_styling ;;
            [Qq])
                configure_application
                configure_api
                configure_frontend
                configure_websocket
                configure_database
                configure_jwt
                configure_asterisk
                configure_sip
                configure_rayanpbx
                configure_security
                configure_pollination
                configure_cli_styling
                ;;
            [Ss])
                save_config
                echo
                read -p "Press Enter to exit..."
                exit 0
                ;;
            [Xx])
                echo -e "${YELLOW}Exiting without saving...${RESET}"
                exit 0
                ;;
            *)
                echo -e "${RED}Invalid option${RESET}"
                sleep 1
                ;;
        esac
    done
}

# Non-interactive mode (for installer script)
non_interactive_mode() {
    local db_password="$1"
    local mysql_root_password="$2"
    local ami_secret="$3"
    
    # Set defaults
    CONFIG[APP_NAME]="${CONFIG[APP_NAME]:-RayanPBX}"
    CONFIG[APP_ENV]="${CONFIG[APP_ENV]:-production}"
    CONFIG[APP_DEBUG]="${CONFIG[APP_DEBUG]:-false}"
    CONFIG[APP_URL]="${CONFIG[APP_URL]:-http://localhost:3000}"
    CONFIG[APP_TIMEZONE]="${CONFIG[APP_TIMEZONE]:-UTC}"
    
    CONFIG[API_HOST]="${CONFIG[API_HOST]:-0.0.0.0}"
    CONFIG[API_PORT]="${CONFIG[API_PORT]:-8000}"
    CONFIG[API_BASE_URL]="http://localhost:${CONFIG[API_PORT]}"
    
    CONFIG[FRONTEND_PORT]="${CONFIG[FRONTEND_PORT]:-3000}"
    CONFIG[FRONTEND_HOST]="${CONFIG[FRONTEND_HOST]:-0.0.0.0}"
    
    CONFIG[WEBSOCKET_HOST]="${CONFIG[WEBSOCKET_HOST]:-0.0.0.0}"
    CONFIG[WEBSOCKET_PORT]="${CONFIG[WEBSOCKET_PORT]:-9000}"
    
    CONFIG[DB_CONNECTION]="${CONFIG[DB_CONNECTION]:-mysql}"
    CONFIG[DB_HOST]="${CONFIG[DB_HOST]:-127.0.0.1}"
    CONFIG[DB_PORT]="${CONFIG[DB_PORT]:-3306}"
    CONFIG[DB_DATABASE]="${CONFIG[DB_DATABASE]:-rayanpbx}"
    CONFIG[DB_USERNAME]="${CONFIG[DB_USERNAME]:-rayanpbx}"
    CONFIG[DB_PASSWORD]="${db_password}"
    
    # Generate JWT secret if not exists
    if [ -z "${CONFIG[JWT_SECRET]}" ] || [ "${CONFIG[JWT_SECRET]}" == "your-super-secret-jwt-key-change-this-in-production" ]; then
        CONFIG[JWT_SECRET]=$(generate_secret)
    fi
    CONFIG[JWT_ALGORITHM]="${CONFIG[JWT_ALGORITHM]:-HS256}"
    CONFIG[JWT_EXPIRATION]="${CONFIG[JWT_EXPIRATION]:-7200}"
    CONFIG[JWT_REFRESH_EXPIRATION]="${CONFIG[JWT_REFRESH_EXPIRATION]:-604800}"
    
    CONFIG[ASTERISK_AMI_HOST]="${CONFIG[ASTERISK_AMI_HOST]:-127.0.0.1}"
    CONFIG[ASTERISK_AMI_PORT]="${CONFIG[ASTERISK_AMI_PORT]:-5038}"
    CONFIG[ASTERISK_AMI_USERNAME]="${CONFIG[ASTERISK_AMI_USERNAME]:-admin}"
    CONFIG[ASTERISK_AMI_SECRET]="${ami_secret:-rayanpbx_ami_secret}"
    CONFIG[ASTERISK_CONFIG_PATH]="${CONFIG[ASTERISK_CONFIG_PATH]:-/etc/asterisk}"
    CONFIG[ASTERISK_PJSIP_CONFIG]="${CONFIG[ASTERISK_PJSIP_CONFIG]:-/etc/asterisk/pjsip.conf}"
    CONFIG[ASTERISK_EXTENSIONS_CONFIG]="${CONFIG[ASTERISK_EXTENSIONS_CONFIG]:-/etc/asterisk/extensions.conf}"
    CONFIG[ASTERISK_LOG_PATH]="${CONFIG[ASTERISK_LOG_PATH]:-/var/log/asterisk}"
    
    CONFIG[SIP_REALM]="${CONFIG[SIP_REALM]:-rayanpbx.local}"
    CONFIG[SIP_TRANSPORT]="${CONFIG[SIP_TRANSPORT]:-udp}"
    CONFIG[SIP_PORT]="${CONFIG[SIP_PORT]:-5060}"
    CONFIG[SIP_CODECS]="${CONFIG[SIP_CODECS]:-ulaw,alaw,g722,opus}"
    
    CONFIG[RAYANPBX_EXTENSION_RANGE_START]="${CONFIG[RAYANPBX_EXTENSION_RANGE_START]:-100}"
    CONFIG[RAYANPBX_EXTENSION_RANGE_END]="${CONFIG[RAYANPBX_EXTENSION_RANGE_END]:-999}"
    CONFIG[RAYANPBX_DEFAULT_TRUNK_PREFIX]="${CONFIG[RAYANPBX_DEFAULT_TRUNK_PREFIX]:-9}"
    CONFIG[RAYANPBX_PAM_ENABLED]="${CONFIG[RAYANPBX_PAM_ENABLED]:-true}"
    
    CONFIG[RATE_LIMIT_LOGIN]="${CONFIG[RATE_LIMIT_LOGIN]:-5}"
    CONFIG[RATE_LIMIT_LOGIN_DECAY]="${CONFIG[RATE_LIMIT_LOGIN_DECAY]:-60}"
    CONFIG[BCRYPT_ROUNDS]="${CONFIG[BCRYPT_ROUNDS]:-12}"
    
    CONFIG[POLLINATION_AI_ENABLED]="${CONFIG[POLLINATION_AI_ENABLED]:-true}"
    CONFIG[POLLINATION_AI_MODEL]="${CONFIG[POLLINATION_AI_MODEL]:-gpt-4}"
    CONFIG[POLLINATION_AI_ENDPOINT]="${CONFIG[POLLINATION_AI_ENDPOINT]:-https://text.pollinations.ai}"
    
    CONFIG[CLI_USE_COLOR]="${CONFIG[CLI_USE_COLOR]:-true}"
    CONFIG[CLI_USE_EMOJI]="${CONFIG[CLI_USE_EMOJI]:-true}"
    CONFIG[CLI_USE_FIGLET]="${CONFIG[CLI_USE_FIGLET]:-true}"
    CONFIG[CLI_USE_LOLCAT]="${CONFIG[CLI_USE_LOLCAT]:-false}"
    
    save_config
}

# Main
load_config

if [ "$#" -ge 3 ] && [ "$3" == "--non-interactive" ]; then
    # Non-interactive mode for installer
    non_interactive_mode "$4" "$5" "$6"
else
    # Interactive TUI mode
    main_menu
fi
