#!/bin/bash

# RayanPBX .env File Normalizer
# Ensures variables are defined before they are referenced in expansions
# This prevents "unbound variable" errors when sourcing .env with set -u

set -euo pipefail

# Colors
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[1;33m'
readonly RESET='\033[0m'

# Canonical variable order based on .env.example
# Variables must be defined before they are referenced
CANONICAL_ORDER=(
    # Application
    "APP_NAME"
    "APP_ENV"
    "APP_KEY"
    "APP_DEBUG"
    "APP_URL"
    "APP_TIMEZONE"
    
    # API Configuration
    "API_HOST"
    "API_PORT"
    "API_BASE_URL"
    
    # Frontend Configuration
    "FRONTEND_PORT"
    "FRONTEND_HOST"
    
    # WebSocket Server (must come before VITE_ variables that reference it)
    "WEBSOCKET_HOST"
    "WEBSOCKET_PORT"
    
    # Database Configuration
    "DB_CONNECTION"
    "DB_HOST"
    "DB_PORT"
    "DB_DATABASE"
    "DB_USERNAME"
    "DB_PASSWORD"
    
    # Redis
    "REDIS_HOST"
    "REDIS_PORT"
    "REDIS_PASSWORD"
    "REDIS_DB"
    "REDIS_CACHE_DB"
    
    # Cache Configuration
    "CACHE_DRIVER"
    "CACHE_PREFIX"
    
    # JWT Authentication
    "JWT_SECRET"
    "JWT_ALGORITHM"
    "JWT_EXPIRATION"
    "JWT_REFRESH_EXPIRATION"
    
    # Session Configuration
    "SESSION_DRIVER"
    "SESSION_LIFETIME"
    "SESSION_DOMAIN"
    "SESSION_SECURE_COOKIE"
    
    # Asterisk Configuration
    "ASTERISK_AMI_HOST"
    "ASTERISK_AMI_PORT"
    "ASTERISK_AMI_USERNAME"
    "ASTERISK_AMI_SECRET"
    "ASTERISK_CONFIG_PATH"
    "ASTERISK_PJSIP_CONFIG"
    "ASTERISK_EXTENSIONS_CONFIG"
    "ASTERISK_LOG_PATH"
    
    # RayanPBX Configuration
    "RAYANPBX_EXTENSION_RANGE_START"
    "RAYANPBX_EXTENSION_RANGE_END"
    "RAYANPBX_DEFAULT_TRUNK_PREFIX"
    "RAYANPBX_PAM_ENABLED"
    
    # SIP Configuration
    "SIP_REALM"
    "SIP_TRANSPORT"
    "SIP_PORT"
    "SIP_CODECS"
    
    # Security
    "RATE_LIMIT_LOGIN"
    "RATE_LIMIT_LOGIN_DECAY"
    "BCRYPT_ROUNDS"
    
    # Pollination.ai Integration
    "POLLINATION_AI_ENABLED"
    "POLLINATION_AI_API_KEY"
    "POLLINATION_AI_MODEL"
    "POLLINATION_AI_ENDPOINT"
    
    # Logging
    "LOG_CHANNEL"
    "LOG_LEVEL"
    "LOG_PATH"
    
    # Mail
    "MAIL_MAILER"
    "MAIL_HOST"
    "MAIL_PORT"
    "MAIL_USERNAME"
    "MAIL_PASSWORD"
    "MAIL_ENCRYPTION"
    "MAIL_FROM_ADDRESS"
    "MAIL_FROM_NAME"
    
    # CLI/TUI Styling
    "CLI_USE_COLOR"
    "CLI_USE_EMOJI"
    "CLI_USE_FIGLET"
    "CLI_USE_LOLCAT"
    
    # Development (must come after variables they reference)
    "VITE_APP_NAME"
    "VITE_API_BASE"
    "VITE_WS_URL"
    
    # Nuxt Frontend Configuration
    "NUXT_PUBLIC_API_BASE"
    "NUXT_PUBLIC_WS_URL"
)

normalize_env_file() {
    local input_file="$1"
    local output_file="${2:-$input_file}"
    local temp_file
    temp_file=$(mktemp)
    
    if [ ! -f "$input_file" ]; then
        echo -e "${YELLOW}Warning: File $input_file does not exist${RESET}" >&2
        return 1
    fi
    
    # Read the file and store key-value pairs
    declare -A env_vars
    declare -A env_comments
    local current_comment=""
    
    while IFS= read -r line; do
        # Store comments
        if [[ $line =~ ^#.*$ ]] || [[ -z $line ]]; then
            if [ -n "$current_comment" ]; then
                current_comment="$current_comment"$'\n'"$line"
            else
                current_comment="$line"
            fi
            continue
        fi
        
        # Parse key=value
        if [[ $line =~ ^([A-Za-z_][A-Za-z0-9_]*)=(.*)$ ]]; then
            local key="${BASH_REMATCH[1]}"
            local value="${BASH_REMATCH[2]}"
            env_vars[$key]="$value"
            if [ -n "$current_comment" ]; then
                env_comments[$key]="$current_comment"
                current_comment=""
            fi
        fi
    done < "$input_file"
    
    # Write header
    cat > "$temp_file" << 'HEADER'
# RayanPBX Configuration
# Generated by RayanPBX Configurator
# Do not edit manually unless you know what you're doing

HEADER
    
    # Write variables in canonical order
    for key in "${CANONICAL_ORDER[@]}"; do
        if [ -n "${env_vars[$key]:-}" ]; then
            # Add section comment if we have one
            if [ -n "${env_comments[$key]:-}" ]; then
                echo "${env_comments[$key]}" >> "$temp_file"
            fi
            echo "${key}=${env_vars[$key]}" >> "$temp_file"
        fi
    done
    
    # Build associative array for O(1) lookups
    declare -A canonical_set
    for key in "${CANONICAL_ORDER[@]}"; do
        canonical_set[$key]=1
    done
    
    # Write any remaining variables not in canonical order at the end
    echo "" >> "$temp_file"
    echo "# Additional variables" >> "$temp_file"
    for key in "${!env_vars[@]}"; do
        # Check if key is in canonical order using O(1) lookup
        if [ -z "${canonical_set[$key]:-}" ]; then
            echo "${key}=${env_vars[$key]}" >> "$temp_file"
        fi
    done
    
    # Move temp file to output
    mv "$temp_file" "$output_file"
    
    echo -e "${GREEN}✅ Normalized $input_file${RESET}"
}

# Main
main() {
    if [ $# -eq 0 ]; then
        echo "Usage: $0 <env_file> [output_file]"
        echo ""
        echo "Normalizes .env file to ensure variables are defined before being referenced."
        echo "If output_file is not specified, modifies the input file in-place."
        exit 1
    fi
    
    normalize_env_file "$@"
}

# Only run main if script is executed directly
if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    main "$@"
fi
